# Generated by Django 6.0.7 on 2026-07-19 22:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crewgallery', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CrewHero',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='সাপ্তাহিক ক্রু মিটিং', max_length=150)),
                ('description', models.TextField(blank=True, default='রোভার স্কাউট কার্যক্রমের স্মৃতি')),
                ('image', models.ImageField(upload_to='crewgallery/hero/')),
            ],
            options={
                'verbose_name': 'Crew Gallery Hero',
                'verbose_name_plural': 'Crew Gallery Hero',
            },
        ),
    ]
