# Generated by Django 6.0.7 on 2026-07-19 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activitypage',
            name='hero_title',
            field=models.CharField(default='আমাদের কার্যক্রম', max_length=150),
        ),
        migrations.AlterField(
            model_name='activitypage',
            name='section_title',
            field=models.CharField(default='আমাদের কার্যক্রম', max_length=150),
        ),
    ]
