# Generated by Django 6.0.7 on 2026-07-19 23:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Council',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='যেমন: ১২তম ক্রু কাউন্সিল', max_length=150)),
                ('year', models.CharField(blank=True, help_text='যেমন: ২০২৫-২৬', max_length=50)),
                ('order', models.PositiveIntegerField(default=0, help_text='ট্যাব ক্রম')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['order', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CouncilMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('senior_rover', 'সিনিয়র রোভার মেট'), ('rover_mate', 'রোভার মেট'), ('assistant_rover_mate', 'সহকারী রোভার মেট')], max_length=30)),
                ('name', models.CharField(max_length=150)),
                ('department', models.CharField(blank=True, max_length=150)),
                ('subgroup', models.CharField(blank=True, max_length=100)),
                ('image', models.ImageField(blank=True, null=True, upload_to='council/members/')),
                ('order', models.PositiveIntegerField(default=0)),
                ('council', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='members', to='councilpage.council')),
            ],
            options={
                'ordering': ['role', 'order'],
            },
        ),
    ]
