# Generated by Django 6.0.7 on 2026-07-20 00:00

import councilpage.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('councilpage', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='councilmember',
            name='image',
            field=models.ImageField(blank=True, help_text='সর্বোচ্চ ৫০০ KB সাইজের ছবি আপলোড করুন', null=True, upload_to='council/members/', validators=[councilpage.models.validate_image_size]),
        ),
    ]
