# Generated by Django 6.0.7 on 2026-07-19 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AboutPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hero_title', models.CharField(default='আমাদের সম্পর্কে', max_length=150)),
                ('hero_description', models.TextField(blank=True)),
                ('hero_image', models.ImageField(upload_to='about/')),
                ('history_title', models.CharField(default='আমাদের ইতিহাস', max_length=150)),
                ('history_paragraph_one', models.TextField(blank=True)),
                ('history_paragraph_two', models.TextField(blank=True)),
                ('history_image', models.ImageField(upload_to='about/')),
                ('mission_section_title', models.CharField(default='আমাদের লক্ষ্য ও উদ্দেশ্য', max_length=150)),
                ('mission_title', models.CharField(default='আমাদের মিশন', max_length=100)),
                ('mission_text', models.TextField(blank=True)),
                ('vision_title', models.CharField(default='আমাদের ভিশন', max_length=100)),
                ('vision_text', models.TextField(blank=True)),
                ('method_title', models.CharField(default='আমাদের পদ্ধতি', max_length=100)),
                ('method_text', models.TextField(blank=True)),
                ('values_title', models.CharField(default='আমাদের মূল্যবোধ', max_length=100)),
                ('values_text', models.TextField(blank=True)),
            ],
        ),
    ]
