# Generated by Django 6.0.7 on 2026-07-19 23:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContactPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hero_title', models.CharField(default='যোগাযোগ করুন', max_length=150)),
                ('hero_description', models.TextField(blank=True, default='আমাদের সাথে যোগাযোগ করতে নিচের ফর্মটি ব্যবহার করুন')),
                ('address', models.TextField(default='মুন্সীগঞ্জ পলিটেকনিক ইন্সটিটিউট, কমলাঘাট, মিরকাদিম, মুন্সীগঞ্জ')),
                ('phone_one', models.CharField(blank=True, max_length=30)),
                ('phone_two', models.CharField(blank=True, max_length=30)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('working_hours', models.CharField(default='শনিবার - বৃহস্পতিবার, সকাল ৯:০০ - বিকাল ৫:০০', max_length=150)),
                ('form_submit_email', models.EmailField(help_text='ফর্ম সাবমিট হলে যে ইমেইলে পাঠাবে', max_length=254)),
                ('map_embed_url', models.URLField(blank=True, help_text='Google Maps embed URL (iframe src)')),
            ],
            options={
                'verbose_name': 'Contact Page',
                'verbose_name_plural': 'Contact Page',
            },
        ),
        migrations.CreateModel(
            name='FAQItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=250)),
                ('answer', models.TextField()),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='SocialLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icon_class', models.CharField(choices=[('fab fa-facebook-f', 'Facebook'), ('fab fa-twitter', 'Twitter'), ('fab fa-instagram', 'Instagram'), ('fab fa-youtube', 'YouTube'), ('fab fa-whatsapp', 'WhatsApp'), ('fab fa-linkedin-in', 'LinkedIn')], max_length=50)),
                ('url', models.URLField()),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['order'],
            },
        ),
    ]
