# Generated by Django 6.0.7 on 2026-08-06 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contactpage', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactpage',
            name='map_embed_url',
            field=models.URLField(blank=True, help_text='Google Maps embed URL (iframe src)', max_length=2000),
        ),
    ]
