# Generated by Django 6.0.7 on 2026-07-19 23:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EventHero',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='আমাদের বিভিন্ন কার্যক্রম', max_length=150)),
                ('description', models.TextField(blank=True, default='রোভার স্কাউট কার্যক্রমের স্মৃতি')),
                ('image', models.ImageField(upload_to='eventgallery/hero/')),
            ],
            options={
                'verbose_name': 'Event Gallery Hero',
                'verbose_name_plural': 'Event Gallery Hero',
            },
        ),
        migrations.CreateModel(
            name='EventImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, help_text='ছবির ক্যাপশন (alt text)', max_length=200)),
                ('image', models.ImageField(upload_to='eventgallery/')),
                ('is_active', models.BooleanField(default=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['order', '-created_at'],
            },
        ),
    ]
