# Generated by Django 6.0.7 on 2026-07-19 17:21

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HomePage', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='homepage',
            old_name='image',
            new_name='hero_image',
        ),
        migrations.AddField(
            model_name='homepage',
            name='about_description_1',
            field=models.TextField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='homepage',
            name='about_description_2',
            field=models.TextField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='homepage',
            name='about_image',
            field=models.ImageField(default=django.utils.timezone.now, upload_to='images/about/'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='homepage',
            name='about_title',
            field=models.CharField(default=django.utils.timezone.now, max_length=150),
            preserve_default=False,
        ),
    ]
