# Generated by Django 6.0.7 on 2026-07-19 17:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('HomePage', '0002_rename_image_homepage_hero_image_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='homepage',
            name='header_text',
        ),
        migrations.RemoveField(
            model_name='homepage',
            name='sub_description',
        ),
        migrations.RemoveField(
            model_name='homepage',
            name='sub_header_text',
        ),
    ]
