# Generated by Django 6.0.7 on 2026-07-19 17:32

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HomePage', '0003_remove_homepage_header_text_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='header_text',
            field=models.CharField(default=django.utils.timezone.now, max_length=50),
            preserve_default=False,
        ),
    ]
