# Generated by Django 6.0.7 on 2026-07-19 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HomePage', '0004_homepage_header_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homepage',
            name='about_title',
            field=models.CharField(default='মুন্সীগঞ্জ পলিটেকনিক ইন্সটিটিউট রোভার স্কাউট গ্রুপ', max_length=150),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='header_text',
            field=models.CharField(default='আমাদের সম্পর্কে', max_length=50),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='title',
            field=models.CharField(default='আলোকিত জীবনের সন্ধানে রোভারিং', max_length=100),
        ),
    ]
