# Generated by Django 6.1 on 2026-08-26 09:07

import django.core.validators
import django.db.models.deletion
import members.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ActivityCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Activity categories',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='MemberProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bs_id', models.CharField(db_index=True, help_text="The member's existing Bangladesh Scouts ID. This is the only member identifier used in this app.", max_length=32, unique=True, verbose_name='BS ID')),
                ('full_name', models.CharField(max_length=150)),
                ('profile_photo', models.ImageField(blank=True, null=True, upload_to=members.models.profile_photo_upload_path, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'webp'])])),
                ('student_id', models.CharField(blank=True, max_length=50, verbose_name='Student ID / Roll Number')),
                ('department', models.CharField(blank=True, db_index=True, max_length=100)),
                ('technology', models.CharField(blank=True, max_length=100, verbose_name='Technology / Trade')),
                ('semester', models.CharField(blank=True, max_length=20)),
                ('session', models.CharField(blank=True, db_index=True, max_length=20)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('email', models.EmailField(blank=True, help_text='Optional if it duplicates the account email.', max_length=254)),
                ('address', models.TextField(blank=True)),
                ('blood_group', models.CharField(blank=True, choices=[('A+', 'A+'), ('A-', 'A-'), ('B+', 'B+'), ('B-', 'B-'), ('AB+', 'AB+'), ('AB-', 'AB-'), ('O+', 'O+'), ('O-', 'O-'), ('unknown', 'Unknown')], default='unknown', max_length=10)),
                ('joining_date', models.DateField(blank=True, null=True)),
                ('registration_number', models.CharField(blank=True, max_length=50)),
                ('biography', models.TextField(blank=True, max_length=1000, verbose_name='Short Biography')),
                ('status', models.CharField(choices=[('current', 'Current Student'), ('passed_out', 'Passed Out')], db_index=True, default='current', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='member_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['full_name'],
            },
        ),
        migrations.CreateModel(
            name='ScoreRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activity_name', models.CharField(max_length=150)),
                ('points', models.IntegerField(validators=[django.core.validators.MinValueValidator(-1000), django.core.validators.MaxValueValidator(1000)])),
                ('activity_date', models.DateField(db_index=True, help_text='The date the activity actually happened / points were earned (not the entry date).')),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('added_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='score_records_added', to=settings.AUTH_USER_MODEL)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='score_records', to='members.activitycategory')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='score_records', to='members.memberprofile')),
            ],
            options={
                'ordering': ['-activity_date', '-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='memberprofile',
            index=models.Index(fields=['status', 'session'], name='members_mem_status_07543d_idx'),
        ),
        migrations.AddIndex(
            model_name='memberprofile',
            index=models.Index(fields=['department', 'session'], name='members_mem_departm_53461a_idx'),
        ),
        migrations.AddIndex(
            model_name='scorerecord',
            index=models.Index(fields=['member', 'activity_date'], name='members_sco_member__b44e1d_idx'),
        ),
        migrations.AddIndex(
            model_name='scorerecord',
            index=models.Index(fields=['category', 'activity_date'], name='members_sco_categor_8865cb_idx'),
        ),
    ]
